### ISSUE TITLE
Add example for using batches if you want to accessing all the genome

### ISSUE THREAD

**Issue by hyanwong** [limix/bgen-reader-py#10]
I'm using the library to iterate over the entire genome. It's *way* faster to do this in batches, rather than calling `.compute()` on each variant in turn. I.e. I now do

`bgen['genotype'][x:(x+batch_size),:,0:2].compute()`

rather than this slow iteration

```
for i in range(x, x+batch_size):
    bgen['genotype'][i,:,0:2].compute()
```

In fact, the `.compute()` call seems takes almost the same time regardless of whether it is getting 1 or 100 variants. It's obvious in hindsight, but it's probably worth saying that in the documentation, or even giving an example. Of course, if the batch size is too high, you run out of memory, so you would have to recommend tweaking this for the machine you are running on. But I had at least a 100x speedup in my code by batching the `.compute()` requests in this way.

**Comment by hyanwong** [comment]
If it is useful, the following function can output the batches to iterate over:

```
def chunkedRange(start,end,step):
    i = start
    j = i+step
    while j < end:
        yield (i,j)
        i, j = j, j+step
    yield (i,end)
```

used like

```
for start,end in chunkedRange(0,len(bgen['genotype']), batch_size):
    genotypes = bgen['genotype'][start:end,:,:].compute()
    #now iterate over genotypes[i,:,:] for i in range(end-start) 
```

**Comment by horta** [comment]
Thanks again for the feedback. I have seen this issue before. It will be solved by opportunistic cache from dask library: http://dask.pydata.org/en/latest/caching.html
However, it is still experimental but might be good enough for the problem at hand:

```
>>> from dask.cache import Cache
>>> cache = Cache(2e9)  # Leverage two gigabytes of memory
>>> cache.register()    # Turn cache on globally
```

I, however, need to do some tests with that caching before adding in the documentation. I prefer this solution over the batch-reading as I might be able to solve that problem without extending the interface.

**Comment by hyanwong** [comment]
Will using cache help if you are only doing a single pass through all variants? How will Dask know to cache e.g. the first 1000 variants if you have only asked for the first one thus far?

**Comment by horta** [comment]
If you ask the first variant, it will load n adjacent variants to fill up the memory passed to bgen_read's parameter `size`:

```
read_bgen(filepath, size=50, verbose=True, metadata_file=True):
```

which defaults to 50 megabytes. That is why when you load, lets say, 100 adjacent variants it is as fast as loading a single one. This is a common practice to take advantage of how hard disks work and how preemptive disk read works.

By enabling dask cache, you can request the first variant, which will load n adjacent ones, and then ask for the second variant, which won't load anything as it is in dask's cache already. This is transparent for the user.

**Comment by hyanwong** [comment]
Ah, I hadn't noticed the "size" parameter. Thanks. That makes sense now.

**Comment by hyanwong** [comment]
I get `ImportError: Cache requires cachey, "No module named 'cachey'" problem importing`, so presumably I need another python module if I am to do this. May be worth mentioning in the docs, or listing as a prerequisite so it automatically gets installed.

**Comment by hyanwong** [comment]
I've tried this out, and it doesn't seem to work. I'm using:

```
from dask.cache import Cache
cache = Cache(10e9)  # Leverage 10 gigabytes of memory
cache.register()    # Turn cache on globally
bgen = read_bgen(bgen_file, verbose=False, size = 1000)
bgen['genotype'][1,:,:].compute(num_workers=40).astype(np.uint8) #this takes > 10 secs
bgen['genotype'][2,:,:].compute(num_workers=40).astype(np.uint8) #this still takes > 10 secs
```

Am I doing something wrong?

**Comment by horta** [comment]
Thanks for the feedback again =) I fixed the problem without cache library. Now `bgen[0]` and `bgen[1]` will imply in only one read. The release version is 1.1.5. Let me know how it goes =)

**Comment by hyanwong** [comment]
Yep, that seems to work now, thanks! However, I'm unclear of the distinction between passing a "size" parameter to read_bgen, and using cache.register(). I'm doing both at the moment, but there must be some strange interaction between the two. Might it be worth documenting best practice for reading large numbers of sequential variants?

**Comment by horta** [comment]
I would avoid fiddling with `size` parameter and definitely not using `cache`. The `size` parameter determines the number of variants that are read from disk in a single request, the `cache` library is something way more complicated and not useful for your case (I just realised it yesterday.)

**Comment by hyanwong** [comment]
Ah, so I should use neither? At the moment I'm reading about 1000 variants per time as a batch, which seems about right, so the default of size=50 seems a little low to me. It's using up about 20-30 GB of the 210 GB memory space on my server, which seems OK.
