### ISSUE TITLE
Error when installing with pip

### ISSUE THREAD

**Issue by dissectroslin** [limix/bgen-reader-py#11]
Hi,

I was trying to install bgen-reader using pip (pip install bgen-reader --user), but at some point, I receive the error:

GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include -I/usr/include -I/usr/local/include -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/bgen_reader._ffi.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/bgen_reader._ffi.o
    build/temp.linux-x86_64-2.7/bgen_reader._ffi.c:492:18: fatal error: bgen.h: No such file or directory
     #include "bgen.h"
                      ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zqQ5TK/bgen-reader/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-YLS4PR/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-zqQ5TK/bgen-reader/

Is there any workaround for this?

Best regards,

**Comment by horta** [comment]
Hi @dissectroslin , I think you are using python 2.7, and therefore pip had to compile the source code instead of downloading the binary. I will have a quick look why I did not support python 2.7 in the first place.

**Comment by horta** [comment]
Ok, could you try again? I just prepare a build for python2.7 for linux and macos.

**Comment by dissectroslin** [comment]
Yes, I am using Python 2.7.

Ok, many thanks.

**Comment by dissectroslin** [comment]
Hi,

Sorry, I see I sent a message out of place.

Yes, apparently it works now for me.

This is great, many thanks for solving this!
