### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by nurfatimaj** [limix/bgen-reader-py#15]
Hello!

I am using the bgen-reader package to read in bgen files to analyse dosage information of certain cases. I have 40,101 people in the sample and 314,926 variants from chromosome X. I have noticed a strange issue. I followed the example on the website and ran these codes

`data = read_bgen(bgen_file, samples_filepath = sample_file)`
`variants = data['variants'].compute()`

The resulting data frame called variants has 314,926 rows, but row index goes only up to 314,350 or something. So, it means that about 600 rows are indexed by the same number, although they contain information on distinct variants (I checked this). I was hoping that this is only a problem in variants dataframe and simply reset the index.

However, now I see it also affects genotypes. If I run `data['genotype'][314604]`, I get back the following output: `Delayed('314604')`. But if I run `data['genotype'][314604].compute()` I get an error message `IndexError: list index out of range`. It seems that the cause of index problem with both variants and genotypes is the same. But I don't know how to fix it for genotype. 

I will be grateful for any comment!

Thank you!

Fatima

**Comment by horta** [comment]
Hi @labuve , thanks a lot for reporting the issue. Is there a way I can have access to the file causing that problem?

**Comment by nurfatimaj** [comment]
Hi, @horta!

Sorry for the delay. I've been checking with my teammates which part of the data I could share. I am afraid I cannot share the whole bgen file with you, but I could share `data['variants']` (i.e., before I passed it to compute() function). And since the indexing is a problem there too, I am hoping this should be sufficient for solving the issue.

I am now just unsure how should I export it out of python. I suppose, I can't just write it to a csv file, right? Do you happen to know some ways?

P. S. Now it's sort of dawning on me that probably sharing `data['variants']` is of no help. But I can't really share the bgen file. Could there be some alternative way?

**Comment by horta** [comment]
No worries. I might have found the problem. Could you try this bgen-reader version?

```
pip install git+https://github.com/limix/bgen-reader-py.git@develop
```

It is supposed to install version ``3.0.5``.

**Comment by nurfatimaj** [comment]
This is the the output with error that gcc is not found. Even though I do have gcc. Here is the output after running `gcc --version`
`gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

The error message is below:

Installing collected packages: bgen-reader
  Found existing installation: bgen-reader 3.0.4
    Uninstalling bgen-reader-3.0.4:
      Successfully uninstalled bgen-reader-3.0.4
  Running setup.py install for bgen-reader ... error
    Complete output from command /panfs/roc/msisoft/anaconda/anaconda3-5.0.1/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-up5y1hx5-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-a1fmz2ct-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_testit.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_samples.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_dosage.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_metadata.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_partition.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_string.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_reader.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/__init__.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_download.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_file.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_helper.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_bgen.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_dask.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/conftest.py -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_genotype.py -> build/lib.linux-x86_64-3.6/bgen_reader
    creating build/lib.linux-x86_64-3.6/bgen_reader/test
    copying bgen_reader/test/test_dosage.py -> build/lib.linux-x86_64-3.6/bgen_reader/test
    copying bgen_reader/test/test_large_file.py -> build/lib.linux-x86_64-3.6/bgen_reader/test
    copying bgen_reader/test/__init__.py -> build/lib.linux-x86_64-3.6/bgen_reader/test
    copying bgen_reader/test/test_interface.py -> build/lib.linux-x86_64-3.6/bgen_reader/test
    copying bgen_reader/test/test_bgen_reader.py -> build/lib.linux-x86_64-3.6/bgen_reader/test
    creating build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/_files.py -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/__init__.py -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    running egg_info
    creating bgen_reader.egg-info
    writing bgen_reader.egg-info/PKG-INFO
    writing dependency_links to bgen_reader.egg-info/dependency_links.txt
    writing requirements to bgen_reader.egg-info/requires.txt
    writing top-level names to bgen_reader.egg-info/top_level.txt
    writing manifest file 'bgen_reader.egg-info/SOURCES.txt'
    reading manifest file 'bgen_reader.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'bgen_reader/athr.dll'
    warning: no files found matching 'bgen_reader/bgen.dll'
    warning: no files found matching 'bgen_reader/zlib.dll'
    warning: no files found matching 'bgen_reader/zstd.dll'
    warning: no files found matching 'example/example.bgen'
    warning: no files found matching 'example/example.py'
    writing manifest file 'bgen_reader.egg-info/SOURCES.txt'
    copying bgen_reader/interface.h -> build/lib.linux-x86_64-3.6/bgen_reader
    copying bgen_reader/_example/complex.23bits.bgen -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/complex.23bits.no.samples.bgen -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/complex.sample -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/example.32bits.bgen -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/haplotypes.bgen -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/haplotypes.bgen.metadata.corrupted -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/haplotypes.bgen.metadata.valid -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    copying bgen_reader/_example/wrong.metadata -> build/lib.linux-x86_64-3.6/bgen_reader/_example
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.6/bgen_reader._ffi.c'
    creating build/temp.linux-x86_64-3.6
    building 'bgen_reader._ffi' extension
    creating build/temp.linux-x86_64-3.6/build
    creating build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6
    gcc -pthread -B /panfs/roc/msisoft/anaconda/anaconda3-5.0.1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/panfs/roc/msisoft/anaconda/anaconda3-5.0.1/include -I/usr/include -I/usr/local/include -I/panfs/roc/msisoft/anaconda/anaconda3-5.0.1/include/python3.6m -c build/temp.linux-x86_64-3.6/bgen_reader._ffi.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/bgen_reader._ffi.o
    build/temp.linux-x86_64-3.6/bgen_reader._ffi.c:492:10: fatal error: bgen.h: No such file or directory
     #include "bgen.h"
              ^~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of bgen-reader
Command "/panfs/roc/msisoft/anaconda/anaconda3-5.0.1/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-up5y1hx5-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-a1fmz2ct-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-up5y1hx5-build/
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by horta** [comment]
Try installing bgen-reader after installing bgen: ``conda install -c conda-forge bgen``

**Comment by nurfatimaj** [comment]
Hi! I installed bgen using conda (but I had to create a new environment) and then tried the previous pip install command. I still get the same error as above.

**Comment by horta** [comment]
Hi! I just created a bgen-reader binary file so you dont need to compile it: https://ufile.io/vsa4a
You can download it and install via: ``pip install name_of_file``
It is for Linux and python 3.6

**Comment by nurfatimaj** [comment]
Hi! Thanks a lot! Maybe one issue why I couldn't install it before was that I had wrong version of Python loaded. Now, I managed to install the version 3.0.5 of bgen-reader. 
There is no error with variant indexing anymore, but when reading genotypes python still complains about index out of range (when above ~314,300). If this is any help the error message is below

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-30-d93a179c5576> in <module>()
      4 counter = 0
      5 
----> 6 for g in map(compute, gsubset):
      7 
      8     # Print information to keep track of execution progress (every 10K SNPs, not to clog up the output space)

~/.local/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

~/.local/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

~/.local/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    460                         _execute_task(task, data)  # Re-execute locally
    461                     else:
--> 462                         raise_exception(exc, tb)
    463                 res, worker_id = loads(res_info)
    464                 state['cache'][key] = res

~/.local/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113 
    114     import pickle as cPickle

~/.local/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

~/.local/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/.local/lib/python3.6/site-packages/bgen_reader/_genotype.py in _read_genotype(i)
     50             bgen_filepath, metafile_filepath, vaddrs, sub_part, spart_size
     51         )
---> 52         return g[m]
     53 
     54     return _read_genotype

IndexError: list index out of range

**Comment by horta** [comment]
Hi again. That was the same problem, in another place. Could you try again? ``pip install git+https://github.com/limix/bgen-reader-py.git@develop``
I think you might want to do ``pip uninstall bgen-reader`` before-hand.

**Comment by nurfatimaj** [comment]
I am sorry again, there is something wrong with installation and gcc and it is not easy for me to fix those errors because I don't have permission rights. Could you please share a link to the wheel again? Thanks!

**Comment by horta** [comment]
Sorry for the delay. Here is the new file: https://ufile.io/nntde
It requires python 3.6.

**Comment by nurfatimaj** [comment]
Thanks a lot! Now there is no error :)

**Comment by horta** [comment]
Thank you, I will release a new version now =)
