### ISSUE TITLE
RuntimeError: Could not open /path/to/test.bgen.metadata

### ISSUE THREAD

**Issue by torstees** [limix/bgen-reader-py#17]
**Describe the bug**
I am upgrading from an older version of the bgen_reader (migrating my code to python 3) and the read_bgen commands no longer work. According to the docs, the metadata file is supposed to be written if it isn't found, but that doesn't seem to be happening. 

To reproduce, simply import and then read bgen on a file without metadata: 
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bgen_reader
>>> bgen = bgen_reader.read_bgen("test.bgen")
setupterm() failed: TERM=xterm-256color not found in database or too generic
Reading samples|===============================================================|
Error: Unrecognized bgen index version: .
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/stuff/python3.7/site-packages/bgen_reader/_reader.py", line 84, in read_bgen
    variants = map_metadata(filepath, metafile_filepath)
  File "/path/stuff/lib/python3.7/site-packages/bgen_reader/_partition.py", line 14, in map_metadata
    with bgen_metafile(metafile_filepath) as mf:
  File "/path/stuff/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/path/stuff/lib/python3.7/site-packages/bgen_reader/_bgen.py", line 22, in bgen_metafile
    raise RuntimeError(f"Could not open {filepath}.")
RuntimeError: Could not open /path/stuff/tests/bedfiles/test.bgen.metadata.

These files worked fine with a version (maybe 1 release after you dropped python 2 support)

**Comment by horta** [comment]
I wonder if `/path/stuff/tests/bedfiles/test.bgen.metadata` might have been generated from an old version of bgen-reader for which the current one cannot read anymore. If you remove that file beforehand, what happens?

**Comment by torstees** [comment]
That was the problem. So, no issue. Sorry about that.

**Comment by horta** [comment]
No worries. Thanks for the feedback.
