### ISSUE TITLE
Can't retrieve large.bgen test file 

### ISSUE THREAD

**Issue by CarlKCarlK** [limix/bgen-reader-py#22]
Hi!

When I try to run 

>    with example_files("large.bgen") as filepath:

from test_large_file, it tries to runs

> 'curl http://rest.s3for.me/bgen/large.bgen.bz2.enc -s | openssl enc -d -pbkdf2 -aes-256-cbc -kfile /Users/horta/pass |bunzip2 > /tmp/tmp49mee87i/large.bgen' 

which fails for lack of a password. (If the large file isn't private, a work around would be just to give me temporary access and I'll make my own copy.)

Thanks,
Carl

**Comment by horta** [comment]
Hi Carl,

Thanks for the interest in the package.

That is a file I got at random from someone (at random) I found in the cluster I use. Since it is not my file (and might have some privacy issues), I decided to encrypt it so only I could use it.

Let me know if i can help you some other way.

**Comment by CarlKCarlK** [comment]
Danilo,

Understood. If you can think of any ways to generate large “random” BGEN files (not necessarily via Python), please let me know. I want to do performance testing and tuning and it’s hard without big data.


  *   Carl

**Comment by horta** [comment]
PLINK2 have some [BGEN support](https://www.cog-genomics.org/plink/1.9/input#oxford). It might be able to generate bgen files.

**Comment by CarlKCarlK** [comment]
@horta, I can now generate random (unphased, 2 allelle, dipoid) bgen files of any dimensions. If you'd like me to generate a new "big file" that you can share, just tell me the desired size. (I'm using qctools to convert a generated text *.gen file to *.bgen.)

**Comment by horta** [comment]
Thats is great, Carlk. I never had access to any very huge bgen file because of privacy issues. I will have a look at the issue you have opened and get back to you as soon as possible. Thanks a lot!
