### ISSUE TITLE
variant position is returning negative numbers

### ISSUE THREAD

**Issue by CarlKCarlK** [limix/bgen-reader-py#24]
On bgen files with pos larger than about 2 billion, the reader returns negative numbers. (Granted this is larger than the largest human chromosome.) 

- Open roundtrip1.bgen in the reader.
- Look at the last pos values and see that they are negative
- list(read_bgen['variants']['pos'])[-5:]
- To confirm that the values are positive in the bgen file, convert it to *.gen
-  /mnt/m/qctool/build/release/qctool_v2.0.7 -g roundtrip1.bgen -og roundtrip2.gen
- Inspect the *.gen file and see that the pos values are positive. (The largest one is 3037630001).
- (The spec says the variant position is an unsigned 32-bit int.)

[temp.zip](https://github.com/limix/bgen-reader-py/files/4296159/temp.zip)

**Comment by horta** [comment]
I finally have time to work on the bgen reader. I will get back here later on. Thanks!

**Comment by horta** [comment]
Thanks a lot, @CarlKCarlK The new bgen C library I'm cooking won't have that problem. I plan to release it today and then work on the bgen-reader-py to use it.

**Comment by CarlKCarlK** [comment]
Awesome!
