### ISSUE TITLE
ci\before-build-win.bat references bgen install.bat that no longer exists

### ISSUE THREAD

**Issue by CarlKCarlK** [limix/bgen-reader-py#27]
Greetings,

The file `bgen-reader-py\ci\before-build-win.bat` calls
`powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/bgen/master/install.bat', 'install-bgen.bat')"`
and then fails because the bgen github project no longer contains an install.bat file.

**Comment by horta** [comment]
Hi Carl,

Can you try

```
curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=bgen bash
```

on a Git bash terminal?

Can I ask why you were using that method of installation? I thought I was the only one using it for testing purpose on CI tools. I can make it work again if the above approach is not desirable.

**Comment by CarlKCarlK** [comment]
[Replied via private email for now. – Carl]
