### ISSUE TITLE
Library fails on *.bgen files larger than 2Gbtyes (2**31)

### ISSUE THREAD

**Issue by CarlKCarlK** [limix/bgen-reader-py#29]
Sorry for another one. Please let me know if you want to work on proposing a fix.

The vaddr variable is an offset into a file and so should be a uint64. (It looks like that is what it is in the C Bgen library). On the Python side, in interface.h, it is 
    long vaddr; /* variant offset-address */
which on most machines is a int32.

I generated a 2500 sample x 500,000 variant (bgen_bits=16) file of size 4.4GB. When I try to access anything past 2TB (2**31), it fails.

- Carl
p.s. I'm happy to test any fixes. Or if you want your own giant test file, I can give instructions on how to generate one with a dev version of PySnpTools.

**Comment by horta** [comment]
It should work now. I'm using proper unsigned integer sizes. Let me know if it does not! =)

**Comment by CarlKCarlK** [comment]
Just test this. It works! Thanks.
