### ISSUE TITLE
Could not open genotype

### ISSUE THREAD

**Issue by fbeghini** [limix/bgen-reader-py#35]
Hi,
I'm trying to load a BGEN file into a ipython session using open_bgen but it fails returning two error
```
ERROR: `max_ploidy` cannot be zero
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-dc223f36040c> in <module>
----> 1 bgen = open_bgen('5c614288-7779-4013-a631-af36bbe743d6.bgen', allow_complex=False,)

/gpfs/milgram/scratch60/christakis/fb343/conda_envs/jupyter/lib/python3.8/site-packages/bgen_reader/_bgen2.py in __init__(self, filepath, samples_filepath, allow_complex, verbose)
    157             self._metadata2_path.unlink()
    158         if not self._metadata2_path.exists():
--> 159             self._create_metadata2()
    160
    161         self._metadata2_memmaps = MultiMemMap(self._metadata2_path, mode="r")

/gpfs/milgram/scratch60/christakis/fb343/conda_envs/jupyter/lib/python3.8/site-packages/bgen_reader/_bgen2.py in _create_metadata2(self)
    170         with MultiMemMap(metadata2_temp, mode="w+") as mmm_wplus:
    171             self._extract_nalleles_ids_etc(mmm_wplus)
--> 172             self._extract_ncombinations_etc(mmm_wplus)
    173             self._extract_samples_etc(mmm_wplus)
    174         os.rename(metadata2_temp, self._metadata2_path)

/gpfs/milgram/scratch60/christakis/fb343/conda_envs/jupyter/lib/python3.8/site-packages/bgen_reader/_bgen2.py in _extract_ncombinations_etc(self, mmm_wplus)
    303             previous_i = None
    304             while i < self.nvariants:
--> 305                 genotype = self._cbgen.read_genotype(mmm_wplus["vaddr"][i])
    306                 ncombinations_memmap[i] = genotype.probability.shape[-1]
    307                 phased_memmap[i] = genotype.phased

/gpfs/milgram/scratch60/christakis/fb343/conda_envs/jupyter/lib/python3.8/site-packages/cbgen/_bgen_file.py in read_genotype(self, offset, precision)
    178         gt: CData = lib.bgen_file_open_genotype(self._bgen_file, offset)
    179         if gt == ffi.NULL:
--> 180             raise RuntimeError(f"Could not open genotype (offset {offset}).")
    181
    182         if precision not in [64, 32]:

RuntimeError: Could not open genotype (offset 4685).
```

I'm using Python 3.8.5 with bgen_reader version 4.0.6

**Comment by CarlKCarlK** [comment]
Thanks for using bgen-reader!

The problem may be a corrupted BGEN file. Can you try to open with our other method and let us know the results?

```
# Try "read_bgen" instead of "open_bgen"
from bgen_reader import read_bgen
bgen = read_bgen('5c614288-7779-4013-a631-af36bbe743d6.bgen', verbose=True)
print(bgen["variants"].head())
geno = bgen["genotype"][0].compute()
print(geno["probs"][0])
```

Thanks,
Carl

**Comment by fbeghini** [comment]
Sorry for the late reply. When running `geno = bgen["genotype"][0].compute()` I get the same exact error reported in the first post.

**Comment by CarlKCarlK** [comment]
Francesco,
If both methods of opening the file are reporting:
```
RuntimeError: Could not open genotype (offset 4685).
ERROR: `max_ploidy` cannot be zero
```
that strongly suggests the file is corrupt. I'll ask Danilo, the project lead, to give an opinion.

- Carl

**Comment by horta** [comment]
Humm I guess it is a bug because the bgen specification explicitly says that

```
The maximum ploidy Pmax of samples in the row. Values between 0 and 63 are allowed.
```

https://www.well.ox.ac.uk/~gav/bgen_format/spec/latest.html

I will fix that on the bgen C library: https://github.com/limix/bgen/blob/e2352c0c2dd9dfa00c7dbbb009e9d867643eee4f/src/layout2.c#L103

It would be great if I could have access to that file, @fbeghini . In any case I will hopefully fix it and post back here with the update so you can test it =) Thanks @CarlKCarlK as well!

**Comment by fbeghini** [comment]
That's great news @horta! Unfortunately, I can't share the file externally, I'm sorry.

**Comment by horta** [comment]
I believe that has been sorted. Let me know otherwise... Thanks!

**Comment by DiegoMac17** [comment]
Hi @horta,
I am experiencing the same issue as fbeghini. I just installed bgen-reader through pip, so it should have the most up-to-date version. Similarly, I unfortunately cannot share the file due to policies of the dataset. 
"ERROR: `max_ploidy` cannot be zero" is displayed when using either of the Dask or the Numpy based methods.
The dataset was generated by a big consortium in my field, so I don't suspect the data would be corrupted, but I could reach out to them in case this is not due to a software issue.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_64301/1789775344.py in <module>
      3 bgen = read_bgen('chr1.bgen', verbose=True)
      4 print(bgen["variants"].head())
----> 5 geno = bgen["genotype"][0].compute()
      6 print(geno["probs"][0])

....
    178         gt: CData = lib.bgen_file_open_genotype(self._bgen_file, offset)
    179         if gt == ffi.NULL:
--> 180             raise RuntimeError(f"Could not open genotype (offset {offset}).")
    181 
    182         if precision not in [64, 32]:

RuntimeError: Could not open genotype (offset 128058).

**Comment by CarlKCarlK** [comment]
Diego,

Thanks for using bgen-reader!

Just to double (triple?) check that you really do have the latest version of things:

cbgen should be 1.0.1
bed-reader should be 4.0.8
(I can check these by going to C:\Users\Carl\miniconda3\envs\gtg2\lib\site-packages and seeing folders cbgen-1.0.1.dist-info and bgen_reader-4.0.8.dist-info.)

OR
>pip freeze | findstr bgen  # or fgrep instead of findstr
bgen-reader==4.0.8
cbgen==1.0.1


  *   Carl

**Comment by DiegoMac17** [comment]
Hi @CarlKCarlK , thank you for your reply!
I checked the version of cbgen and bed-reader, I have cbgen 1.0.1, bgen-reader 4.0.8 and bgen 4.1.3.
I am working on a linux server and installed bgen-reader using conda, in case this could have any effect.

**Comment by CarlKCarlK** [comment]
That versioning all looks good as far as I can tell.
Until @horta can respond, I wonder if you can ask your consortium for a non-private sample file.
Being able to reproduce the problem would make fixing it easier.
- Carl

**Comment by DiegoMac17** [comment]
Hi @CarlKCarlK, sorry for the late reply. The consortium finally replied to me, and they are not able to share with us a non-private sample file. Nevertheless they have recommended me to use QCtools v2 to perform the conversion from bgen to PLINK.
Thank you!

**Comment by CarlKCarlK** [comment]
Diego,

I'm glad you have a path forward. If you need to read PLINK BED files, I have a library for that:
https://pypi.org/project/bed-reader/

Aside: I'm surprised the BGEN data can be translated to PLINK format. My understanding is that BGEN files are usually used when there are probabilities in the data and PLINK BED is for when the readings are definite.


  *   Carl

**Comment by horta** [comment]
Sorry about the long delay!

**Comment by horta** [comment]
The problem is that you need to update bgen-reader to 4.0.8. Pypi: https://pypi.org/project/bgen-reader/

You can do that from terminal:

```
pip install bgen-reader --upgrade
```

That is a bug that I've fixed in one of those two previous versions.

**Comment by horta** [comment]
Also notice that you can check its version by doing:

```
import bgen_reader
print(bgen_reader.__version__)
```

**Comment by DiegoMac17** [comment]
@horta Thank you for your reply!
I actually I have the 4.0.8 version of bgen-reader, and to be sure I have verified it by using the print(bgen_reader.__version__) command.
The error takes place in the line geno = bgen["genotype"][0].compute()
and the cell shows the following:

Mapping genotypes: 100%|██████████████████████████████████████████████████████████| 45378/45378 [00:02<00:00, 18678.47it/s]
ERROR: `max_ploidy` cannot be zero
....
RuntimeError: Could not open genotype (offset 128058).

Is there maybe another package I should up/down-grade?

**Comment by horta** [comment]
That is very odd. I will check it now.
