### ISSUE TITLE
index out of range in bgen["variants"]

### ISSUE THREAD

**Issue by ScarlettWang532** [limix/bgen-reader-py#37]
Hi,
I am using the bgen_reader package to read bgen files in and computed it into dosage value. I have 5089 samples and 400,000 variants when i try to do this. But i have met a strange issue. I ran code like follows:

bgen=read_bgen(bgen_file,verbose=False)
variants=bgen['variants'].compute()

The resulting data frame called variants has 400,000 rows, but the row index goes only up to 632. It seems many rows are indexed by the same number, although they are indeed different variants. It seems like related to the npartitions in the Dask DataFrame Structure variable called bgen["variants"]:

bgen["variants"]
Dask DataFrame Structure:
                     id    rsid   chrom    pos nalleles allele_ids  vaddr
npartitions=632                                                          
0                object  object  object  int64    int64     object  int64
633                 ...     ...     ...    ...      ...        ...    ...
                ...     ...     ...    ...      ...        ...    ...
399423              ...     ...     ...    ...      ...        ...    ...
399999              ...     ...     ...    ...      ...        ...    ...
Dask Name: from-delayed, 1264 tasks

bgen['variants'].compute()
     id             rsid chrom       pos  nalleles allele_ids       vaddr
0     1     1:754198:A:G     1    754198         2        A,G          60
1     1     1:762330:G:T     1    762330         2        G,T         632
2     1     1:764074:T:C     1    764074         2        T,C        1974
3     1     1:791420:A:C     1    791420         2        A,C        2631
4     1     1:792643:A:G     1    792643         2        A,G        2988
..   ..              ...   ...       ...       ...        ...         ...
572  21  21:30030111:A:G    21  30030111         2        A,G  1121838554
573  21  21:30030207:T:C    21  30030207         2        T,C  1121839479
574  21  21:30031175:C:T    21  30031175         2        C,T  1121840770
575  21  21:30035212:G:A    21  30035212         2        G,A  1121842971
576  21  21:30038641:C:T    21  30038641         2        C,T  1121843427

[400000 rows x 7 columns]

Thus when i ran 

compute_dosage(allele_expectation(bgen, any int >632 )) 

would got an error message:
nalleles = bgen["variants"].loc[variant_idx, "nalleles"].compute().values[0]; 
IndexError: index 0 is out of bounds for axis 0 with size 0. 

I don't how to deal with these. I will be very grateful for any comment!

Thank you!

SijiaWang

**Comment by CarlKCarlK** [comment]
Sijia,

Thanks for using bgen-reader!

Just to get more information, can you try finding the dosage using the 2nd (Numpy-based) API?<https://bgen-reader.readthedocs.io/en/latest/numpyapi-api.html#bgen_reader._bgen2.open_bgen.allele_expectation> Here is some sample code for finding dosage for the first 10 variants.
[You can adjust the "slicer" to do any range of variants (or leave it out to do all in one go.)]


  *   Carl

from bgen_reader import example_filepath, open_bgen
filepath = example_filepath("example.32bits.bgen")
# Read the example.
bgen = open_bgen(filepath, verbose=False)
print(bgen.shape)

Output:(500, 199, 3)


import numpy as np



# Find the expectation for all samples and the first 10 variants

slicer = np.s_[:,:10]

e = bgen.allele_expectation(slicer)

print(e.shape)

Output: (500, 10, 2)


# Compute the dosage when considering the allele

# in position 1 as the reference/alternative one.

alt_allele_index = 1

dosage = e[...,1]

print(dosage.shape)

print(dosage)
Output:


(500, 10)

[[       nan 1.98779296 0.01550294 ... 1.9857788  1.010498   0.02685626]

 [1.93575854 1.97802735 0.99383543 ... 1.99118043 0.98992923 1.01315304]

 [1.91558579 0.02111815 1.97933958 ... 0.98950231 0.99530016 0.02114869]

 ...

 [1.94351192 1.95492412 1.98681641 ... 1.97589107 1.00149531 1.98995971]

 [0.10894776 1.00897216 1.99041748 ... 1.99090549 1.01464846 1.00305176]

 [1.01101689 1.02255316 1.99603272 ... 1.99212646 0.99887085 1.96563714]]

**Comment by ScarlettWang532** [comment]
Sorry for the delay. Thanks a lot! I have tried it and "open_bgen" works :), Thanks for your help again!

**Comment by CarlKCarlK** [comment]
That's Great!. Thanks for using Bgen Reader.


  *   Carl

p.s. For anyone looking at this in the future, here is how to do the task using the Dask-inspired API. (It takes a few more steps than using the NumPy API, so I'd recommend the NumPy API for this task.)

from bgen_reader import read_bgen, example_filepath
from bgen_reader import allele_expectation, allele_frequency
filepath = example_filepath("example.32bits.bgen")
bgen = read_bgen(filepath, verbose=True)
variants = bgen["variants"]

import numpy as np



# Find the expectation for all samples and the first 10 variants

slicer = np.s_[:10]



# Compute the dosage when considering the allele

# in position 1 as the reference/alternative one.

alt_allele_index = 1



variant = variants.loc[slicer].compute()

dosage_list = []

for variant_idx in variant.index[:-1]: #Dask indexes include an extra item, so ignore it

    e = allele_expectation(bgen, variant_idx)

    dosage_list.append(e[:,alt_allele_index])

dosage = np.c_[dosage_list].T

print(dosage.shape)

print(dosage)
Output:

(500, 10)

[[       nan 1.98779296 0.01550294 ... 1.9857788  1.010498   0.02685626]

 [1.93575854 1.97802735 0.99383543 ... 1.99118043 0.98992923 1.01315304]

 [1.91558579 0.02111815 1.97933958 ... 0.98950231 0.99530016 0.02114869]

 ...

 [1.94351192 1.95492412 1.98681641 ... 1.97589107 1.00149531 1.98995971]

 [0.10894776 1.00897216 1.99041748 ... 1.99090549 1.01464846 1.00305176]

 [1.01101689 1.02255316 1.99603272 ... 1.99212646 0.99887085 1.96563714]]
