### ISSUE TITLE
Saving metadata in different dir as bgen file

### ISSUE THREAD

**Issue by evigorito** [limix/bgen-reader-py#38]
Thanks for making this library. I am starting to use it but my bgen files are saved in a location that I can't write. Is there any way to store the metadata file for speedy access in a different directory as the bgen files?

As expected, I get the following message

warnings.warn(_metafile_nowrite_dir.format(filepath=metafile), UserWarning)

Many thanks in advance,

Elena

**Comment by CarlKCarlK** [comment]
Elena,

Thanks for using bed-reader!

Are you using "open_bgen" (NumPy-Inspried) or "read_bgen" (Dask-Inspried)?

About how many bgen files are you working with and about how individuals and variants in a file?
About how many variants will you be reading?

I'm hoping to be able to provide a work around that you can use soon and that we can then later add to the main package.


  *   Carl

p.s. I'm about to go out, should be able to look at this later today.


Carl Kadie, Ph.D.
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

**Comment by evigorito** [comment]
Thanks very much for your quick answer. I am working with UKBB bgen files, one per chromosome (22 in total). About 500K individuals and millions of variants. 

I am going to compute different types of polygenic scores (pgs). So for each one I will need to extract about 500K variants per chromosome. Then, I will need to repeat a similar extraction process with different variants. 

I was thinking on creating an open_bgen call for each chromosome and save the metadata so I can then access the variants I need. I may need to split each pgs into multiple  jobs as probably genotype data for 500K variants for 500K individuals uses too much memory but I am okay with that. 

Thanks very much in advance!

**Comment by evigorito** [comment]
Sorry, I forgot to say that I was planning to use the "open_bgen" (NumPy-Inspried)  because I understood may be more appropriate for my needs.

**Comment by CarlKCarlK** [comment]
Elena,

OK. I think I've got it. Sample code is below. (If my paths look funny, it's because I develop first on Windows.)

It turns out that the project lead, Danilo, already included code for your scenario. So, I just had to get it working nicely with the NumPy-inspired API.
The main step is to set the BGEN_READER_CACHE_HOME environment variable to a folder that can contain the metadata.
Also, it helps if the bgen file name contains no path, so "os.chdir" does the trick.

Let me know if this works for you or if you have other questions or issues.


  *   Carl

import os

# If the bgen file is read-only, will put metadata files in
# in BGEN_READER_CACHE_HOME / metadata
# This must be set BEFORE anything is imported from open_bgen
os.environ["BGEN_READER_CACHE_HOME"] = r"M:\deldir"

from bgen_reader import open_bgen

# Best to change to bgen file's dir
os.chdir(r"M:\deldir\02162021")

filename = r"1000x500000.bgen"
bgen2 = open_bgen(filename, verbose=True)
print(bgen2.nsamples)

**Comment by evigorito** [comment]
Hi Carl,

Thanks very much for your help. Your instructions were very clear but I think I am doing something wrong because I am still getting the same error message:

 UserWarning: You don't have permission to write `chr22_v3.bgen.metadata2.mmm`. This might prevent speeding-up the reading process
in future runs.


**This is what I am doing:**
import os
from bgen_reader import open_bgen

_set dir to save metadata_
os.environ["BGEN_READER_CACHE_HOME"] = "/scratch/elena/meta_data_bgen_py" 
(I do have writing permissions on this folder drwxrwxr-x 2 elena elena 4096 Feb 17 09:48 meta_data_bgen_py)

os.chdir("/scratch/bgen_files")

bgen_name = "chr22_v3.bgen"

b_test =  open_bgen(bgen_name , verbose=True)

UserWarning: You don't have permission to write `chr22_v3.bgen.metadata2.mmm`. This might prevent speeding-up the reading process
in future runs.

  warnings.warn(_metafile_nowrite_dir.format(filepath=metafile), UserWarning)
Writing variants|===================================================|   0 secs
metadata -- time=0:01:32.30, 'ids': part 1,121 of 1,121
metadata -- time=0:00:00.38, 'generate samples': part 487,409 of 487,409
metadata -- time=0:00:00.15, 'sample range': part 487,409 of 487,409

Thanks very much in advance

**Comment by CarlKCarlK** [comment]
Elena,

I think you just need to set the environment variable before the "from bgen_reader import open_bgen" line.

import os
# This environ must be set BEFORE anything is imported from bgen_reader
os.environ["BGEN_READER_CACHE_HOME"] = "/scratch/elena/meta_data_bgen_py"
from bgen_reader import open_bgen

If you want, you can set it before you even run Python with something like this (assuming you are on Linux using the bash shell)
      export BGEN_READER_CACHE_HOME=/scratch/elena/meta_data_bgen_py

I think that will work, but if it doesn't, add the lines in the "p.s." before the "open_bgen". They will tell where it is looking for the metadata file.


  *   Carl

p.s.
        from bgen_reader._metafile import infer_metafile_filepath

        metadata_file = infer_metafile_filepath(pathlib.Path(bgen_name))
        print(metadata_file)

**Comment by evigorito** [comment]
Hi Carl,

Many thanks indeed for all your help. I think it is working but I get an odd warning message... sorry...

I have set BGEN_READER_CACHE_HOME in my .bashrc file.

In python

import os
>>> os.environ.get("BGEN_READER_CACHE_HOME")
'/scratch/elena/meta_data_bgen_py'

import pathlib
from bgen_reader._metafile import infer_metafile_filepath
metadata_file = infer_metafile_filepath(pathlib.Path(bgen_name))

when I execute metadata_file = infer_metafile_filepath(pathlib.Path(bgen_name))
I get 
>>>  /home/elena/miniconda3/lib/python3.8/site-packages/bgen_reader/_metafile.py:101: UserWarning: You don't have permission to write `chr22_v3.bgen.metafile`. This might prevent speeding-up the reading process
in future runs.

  warnings.warn(_metafile_nowrite_dir.format(filepath=metafile), UserWarning)

print(metadata_file)
>>> /scratch/elena/meta_data_bgen_py/metafile/chr22_v3.bgen.metafile

but I have a file in the right directory which seems okay, so I guess is just a warning that I shouldn't have?

ls  -ll /scratch/elena/meta_data_bgen_py/metafile/chr22_v3.bgen.metadata2.mmm
-rw-rw-r-- 1 elena elena 5827336285 Feb 17 16:15 ukb_imp_chr22_v3.bgen.metadata2.mmm

Thanks so much for your help, I think this module is amazing. I was using an R counterpart which in my hands it is much slower.

**Comment by CarlKCarlK** [comment]
If it is running fast
  ["Fast" means that it takes a while to create the original .mmm file, but after that it can report the nsamples instantly]
I think you can ignore the warning message.

Thanks for using bgen-reader!


  *   Carl
p.s. I'll be away for several hours.
