### ISSUE TITLE
Retrieving all genotypes for a single sample is very slow

### ISSUE THREAD

**Issue by arinbjornk** [limix/bgen-reader-py#4]
It looks like the current implementation is optimised to retrieve a single genotype for all samples. For my data, the example case `print(bgen['genotype'][0].compute())` is very fast, but `print(bgen['genotype'][:, 0].compute())` is extremely slow and often exhausts all memory.

My guess is that the dask array chunk size is set so that single genotype retrieval is optimised. Could we have an option to optimise retrieval of all genotypes for a given list of samples? Or is there a better way to print/get all genotypes for a single sample?

**Comment by horta** [comment]
Hi @arinbjornk 
I'm sorry about that slowness. However, the bgen format itself was designed to be fast for selecting genotypes specifically. It stores a chunk of all the samples for a given genotype, in a compressed way. This means that selecting a all the genotypes of a given sample requires to load and uncompress the entire file. This is a limitation of bgen format itself.

If that operation is necessary, I recommend you to save into another file format (hdf5, for example) by reading genotype by genotype.

**Comment by arinbjornk** [comment]
Thank you for the quick reply. Unfortunately the model I'm building requires that the data be fed in sequentially by each individual/sample. Your idea of converting it to hdf5 is probably the best way forward for me.

Thanks.
