### ISSUE TITLE
GitHub Action python-package.yml seems to have rotted

### ISSUE THREAD

**Issue by CarlKCarlK** [limix/bgen-reader-py#43]
I don't think python-package.yml works anymore for any branch.

When I check in (a minor change on a branch) and python-package.yml runs, it gets error from `--use-feature=in-tree-build`,
which I think [is now obsolete](https://github.com/libAtoms/QUIP/issues/345). 

When I remove that and check in, I get a flake8 error on a file that I haven't changed:

```
Run flake8 .
would reformat bgen_reader/test/write_random.py
```
(I haven't been able to repro this under Ubuntu & Miniconda 3.9 or Windows and Conda 3.7)

**Comment by CarlKCarlK** [comment]
Addressed by https://github.com/limix/bgen-reader-py/pull/44

**Comment by horta** [comment]
Updated it =)
