### ISSUE TITLE
example_filepath reports AWS error

### ISSUE THREAD

**Issue by CarlKCarlK** [limix/bgen-reader-py#48]
If we run the first example from documentation, it fails:

```
from bgen_reader import example_filepath
bgen_file = example_filepath("example.bgen")

# Read from the file
from bgen_reader import open_bgen
bgen = open_bgen(bgen_file, verbose=False)
probs0 = bgen.read(0)   # Read 1st variant
print(probs0.shape)     # Shape of the NumPy array
# (500, 1, 3)
probs_all = bgen.read() # Read all variants
print(probs_all.shape)  # Shape of the NumPy array
# (500, 199, 3)
```

```
HTTPError: 404 Client Error: Not Found for url: https://bgen-examples.s3.amazonaws.com/example.bgen
```

@horta If you'd like me to switch it to use POOCH (as per issue #31 ), assign it to me and let me know.

-- Carl

**Comment by horta** [comment]
Hi @CarlKCarlK , please do =)
Also, that `example.bgen` is not available anymore at that address :/

Need to check it when I'm home. I might have the backup of those files...

**Comment by CarlKCarlK** [comment]
@horta ,

I have many copies of it (It is 650KB in size, right?)

One downside to using pooch: It adds a dependency that users may not like.

(A potential user of bed-reader [not to be confused with bgen-reader], said he didn’t want to take a dependency on bed-reader because it would add a dependency on pooch (and also Pandas)).

**Comment by CarlKCarlK** [comment]
I have many copies of it (It is 650KB in size, right?)

One downside to using pooch: It adds a dependency that users may not like.

(A potential user of bed-reader [not to be confused with bgen-reader], said he didn’t like want to take a dependency on bed-reader because it would add a dependency on pooch (and also Pandas)).

**Comment by horta** [comment]
Merged =)
