### ISSUE TITLE
Version 1.0.1 won't run unless you manually install everything

### ISSUE THREAD

**Issue by torstees** [limix/bgen-reader-py#5]
It appears that the latest version of bgen at conda is 0.1.16 (with no bgen_reader available there despite the docs suggesting otherwise). The current version of bgen_reader expects version libbgen 1.0.1. As a result, libbgen refuses to load. 

The only way I was able to do this without installing all of the pieces manually was to: 
*   Install bgen via the conda package manager (which also installed all dependencies)
*   Have pip uninstall bgen_reader 1.0.1 and download the version 0.1.16 and install that one

This is all from OSX using the most recent version of conda and python 2.7.x

**Comment by horta** [comment]
Hi @torstees, thanks a lot for the feedback! I have been working on this issue today. I submitted a 1.0.0 bgen release to conda-forge, which is already ready for Linux and Windows and it will soon ready for OSX (https://anaconda.org/conda-forge/bgen).

I also made changes in the bgen-reader Python package documentation, and released the 1.0.3 version, to explain a simpler installation process:

```
conda install -c conda-forge bgen
pip install bgen-reader
```

The first command will install the C library, while the second one will install the Python library.

**Comment by torstees** [comment]
For whatever it’s worth, I was able to upgrade to the newest version of bgen-reader once I installed an older version. It must be related to some dependency tied to the newest setup configuration…maybe?

I
On Jan 27, 2018, at 7:30 PM, Danilo Horta <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @torstees<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftorstees&data=02%7C01%7Ceric.s.torstenson%40vanderbilt.edu%7C8d27ccae79b340d0cfa008d565eec7b4%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636526998593491793&sdata=tZG4yDWnLWvlZ%2BxlnceyIli6E9UaSRCyLXfg%2F0o9gq8%3D&reserved=0>, thanks a lot for the feedback! I have been working on this issue today. I submitted a 1.0.0 bgen release to conda-forge, which is already ready for Linux and Windows and it will soon ready for OSX (https://anaconda.org/conda-forge/bgen<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fanaconda.org%2Fconda-forge%2Fbgen&data=02%7C01%7Ceric.s.torstenson%40vanderbilt.edu%7C8d27ccae79b340d0cfa008d565eec7b4%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636526998593491793&sdata=Xi4coSzxftB%2BLn2jVB8eDYcYhSuOaK4Ryir99U7Q208%3D&reserved=0>).

I also made changes in the bgen-reader Python package documentation, and released the 1.0.3 version, to explain a simpler installation process:

conda install -c conda-forge bgen
pip install bgen-reader


The first command will install the C library, while the second one will install the Python library.

**Comment by horta** [comment]
It might be because the release was still being prepared. That is my guess at least.
